#!/usr/bin/env bash
# The offline half of the test set: everything that needs nothing but this
# checkout, a compiler and e2fsprogs.
#
# This is the script the CI workflow runs. The YAML holds no logic at all --
# it installs e2fsprogs and calls this -- so "green locally" and "green in CI"
# are the same claim, checkable before pushing with:
#
#     make ci-offline
#
# What is deliberately NOT here, and why:
#
#   * anything that needs a Linux kernel to check our answer against (LUKS
#     containers, crash consistency, reordered writes, the Linux differential,
#     replay speed). GitHub's macOS runners have no Docker, so those five run
#     on the ubuntu runner instead -- scripts/ci_linux.sh, where the kernel is
#     the machine rather than a container.
#   * anything that needs a signed, installed, user-approved FSKit extension
#     (mounted driver, mounted LUKS, newfs, kill-recovery, scale) or hands on
#     a USB stick (pull). No runner can grant an extension approval.
#   * anything that needs Homebrew LLVM (the libFuzzer harness). It gets its
#     own job, so a runner without the runtime cannot turn the whole matrix
#     red.
#
# So this is not "the test suite". It is the part of it that can be made
# un-forgettable, which is a different and smaller thing -- `make validate`
# on the developer's Mac stays the full claim. (docs/ENVELOPE.md, which will
# say so in prose, is Part C and is not written yet.)
#
# Exit status and the SKIP rule are the stage runner's; see scripts/ci_stages.sh.
set -uo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# The stage runner -- deadlines, per-suite logs, the tally -- is shared with
# the Linux oracle set, so both print the same summary and "green" means the
# same thing on both machines.
SET_LABEL="offline"
OUT="$ROOT/build/ci"
. "$ROOT/scripts/ci_stages.sh"

ci_begin

# ---------------------------------------------------------------- the set --

# First, and before anything is built: does the patch set reproduce the tree
# we are about to compile? A green run of a tree that only exists on one
# machine is the most expensive kind of pass, and it is the exact failure a
# CI system is supposed to make impossible.
stage check-patches  bash scripts/check_patches.sh

stage build          make tools

# The shipping library, and what must not be in it: no getenv, no test-only
# exports. Needs `make core`, which `make tools` does not build.
stage ship-surface   make check-ship-surface

# Known-answer tests for AES-XTS and the LUKS key derivation, against vectors
# generated by OpenSSL. Links nothing else; runs in a second.
stage crypto         make test-crypto

stage read           bash Tests/run_tests.sh
stage write          bash Tests/run_write_tests.sh
stage bounds         bash Tests/run_bounds_tests.sh

# format and orphan each have one section that wants Docker and skip just
# that section, so they belong here: what they lose on a runner is the Linux
# cross-check, not the suite.
stage format         bash Tests/run_format_tests.sh
stage orphan         bash Tests/run_orphan_tests.sh
stage prealloc       bash Tests/run_prealloc_tests.sh
stage revoke         bash Tests/run_revoke_tests.sh
stage eio            bash Tests/run_eio_tests.sh
stage csum           bash Tests/run_csum_tests.sh
stage fragmentation  bash Tests/run_fragmentation_tests.sh

# Mutated images against the offline driver. Needs no special toolchain, which
# is why it can be here at all -- the in-process libFuzzer harness gets its
# own job, so a runner without the runtime cannot turn this one red.
stage fuzz           bash Tests/run_fuzz_tests.sh
stage hostile        bash Tests/run_fuzz_regressions_tests.sh

# Does the Swift half still compile? This is the canary for the runner image
# having an SDK with FSKit in it: if `macos-15` ever ships an SDK without it,
# this is the stage that says so, in one line, instead of the app build
# failing in a hundred.
stage typecheck      make typecheck

# And does the bundle build at all -- unsigned, no profile, no secrets. Signing
# is release-only (F4); this asks the cheaper question, which is whether the
# extension and the container app still link.
stage app            make app

# The extension's only way to tell a person anything: what it writes when it
# refuses a volume, and what the app reads back. Offline, which is the point --
# the parts of that channel most likely to be wrong (a torn read, a log that
# never stops growing, a device name that becomes a path) need no FSKit.
#
# After `app`, not before: the reader half of this suite runs the built
# Ext4Mac binary, and having it build the bundle first would turn the stage
# above into a cache hit that proves nothing.
stage events         bash Tests/run_events_tests.sh

# Suites added by later phases. Each is listed the day it exists, so that
# forgetting to register one shows up as a shorter summary rather than as
# nothing at all:
#   stage envelope         make test-envelope          (C)
#   stage uninstall        make test-uninstall         (D)

# ------------------------------------------------------------------ tally --
ci_end
