//
//  cryptotest.c
//  SPDX-License-Identifier: GPL-3.0-or-later
//
//  Known-answer tests for the crypto primitives.
//
//  The vectors are not hand-copied from a specification -- they are generated
//  by OpenSSL, through python-cryptography, by Tests/gen_xts_vectors.sh. A test
//  vector transcribed by hand is a test of the transcription, and a wrong one
//  is worse than none: it would be "verified" against our own mistake.
//
//  Each case fixes a key, a sector number and a sector size; the plaintext is
//  generated by the formula below, encrypted, and the SHA-256 of the result
//  compared. Decryption is then checked to round-trip back to the plaintext,
//  so a symmetric error cannot hide.
//
#include "aes_xts.h"
#include "json.h"

#include <CommonCrypto/CommonDigest.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int passed = 0, failed = 0;

static void ok(const char *what)   { passed++; printf("  \033[32mok\033[0m   %s\n", what); }
static void bad(const char *what, const char *detail)
{
    failed++;
    printf("  \033[31mFAIL\033[0m %s\n", what);
    if (detail) printf("         %s\n", detail);
}

static size_t unhex(const char *hex, uint8_t *out, size_t max)
{
    size_t n = strlen(hex) / 2;
    if (n > max) n = max;
    for (size_t i = 0; i < n; i++) {
        unsigned v = 0;
        sscanf(hex + 2 * i, "%2x", &v);
        out[i] = (uint8_t)v;
    }
    return n;
}

static void hexify(const uint8_t *in, size_t n, char *out)
{
    static const char *d = "0123456789abcdef";
    for (size_t i = 0; i < n; i++) {
        out[2*i]     = d[in[i] >> 4];
        out[2*i + 1] = d[in[i] & 0xF];
    }
    out[2*n] = 0;
}

struct xts_case {
    const char *name;
    const char *key_hex;
    uint64_t    sector;
    size_t      size;
    const char *ct_sha256;
};

static const struct xts_case xts_cases[] = {
    /* generated by OpenSSL via python-cryptography; see Tests/gen_xts_vectors.sh */
    { "aes128, sector 0",
      "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
      0ULL, 512,
      "b07f132c9c3990fd181cbf9450b06b3b4c7adcea2ec8f15453204ef242a2ff56" },
    { "aes128, sector 1",
      "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f",
      1ULL, 512,
      "d605c4ac35043b63c11a0bb32477b53a978e40e15c213e71dc940621591e1735" },
    { "aes256, sector 0",
      "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f",
      0ULL, 512,
      "946fbdba2563fc8a123fa5e2e7045f22a0e300d7760037efba7f6f9359a253fb" },
    { "aes256, sector 1",
      "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f",
      1ULL, 512,
      "2c7d6963aec84ce5663f36f4022526583ea2d09673bae46ef2d66b3edd1d87f0" },
    { "aes256, sector 42",
      "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f",
      42ULL, 512,
      "9c371bc8c0c2c0973ddc2a4e88ea9488bd089e1e4771a0a4b9ef59258613bc27" },
    { "aes256, 40-bit sector",
      "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f",
      4886718345ULL, 512,
      "0165710cfe93b5c1f1c835f7d49a98950d49a86dd44cb538478ddcc2e582696d" },
    { "aes256, 4096-byte sector",
      "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f",
      8ULL, 4096,
      "5770bfc157eb1949722e9de91fca7bf641da1effc5cbb94e34677c7c7878edae" },
};

int main(void)
{
    printf("########## CRYPTO PRIMITIVES ##########\n\n");
    printf("AES-XTS against OpenSSL-generated vectors\n\n");

    for (size_t c = 0; c < sizeof(xts_cases)/sizeof(xts_cases[0]); c++) {
        const struct xts_case *tc = &xts_cases[c];
        uint8_t key[64];
        size_t key_len = unhex(tc->key_hex, key, sizeof(key));

        aes_xts_key *k = aes_xts_key_create(key, key_len);
        if (!k) { bad(tc->name, "key rejected"); continue; }

        uint8_t *buf = malloc(tc->size);
        uint8_t *pt  = malloc(tc->size);
        for (size_t i = 0; i < tc->size; i++)
            pt[i] = (uint8_t)((i * 7 + 13) & 0xFF);
        memcpy(buf, pt, tc->size);

        uint8_t tweak[16];
        aes_xts_plain64_tweak(tc->sector, tweak);

        if (aes_xts_crypt_sector(k, true, tweak, buf, tc->size) != 0) {
            bad(tc->name, "encrypt failed");
            goto next;
        }

        uint8_t digest[CC_SHA256_DIGEST_LENGTH];
        CC_SHA256(buf, (CC_LONG)tc->size, digest);
        char got[2 * CC_SHA256_DIGEST_LENGTH + 1];
        hexify(digest, sizeof(digest), got);

        if (strcmp(got, tc->ct_sha256) != 0) {
            char detail[192];
            snprintf(detail, sizeof(detail), "ciphertext sha256\n           want %s\n           got  %s",
                     tc->ct_sha256, got);
            bad(tc->name, detail);
            goto next;
        }

        /* And back again, so a bug that is symmetric cannot pass. */
        if (aes_xts_crypt_sector(k, false, tweak, buf, tc->size) != 0) {
            bad(tc->name, "decrypt failed");
            goto next;
        }
        if (memcmp(buf, pt, tc->size) != 0) {
            bad(tc->name, "decrypt did not round-trip");
            goto next;
        }
        ok(tc->name);

    next:
        free(buf); free(pt);
        aes_xts_key_destroy(k);
    }

    printf("\nrejections\n\n");
    {
        uint8_t key[64] = {0};
        if (aes_xts_key_create(key, 31) == NULL) ok("a key of the wrong length is refused");
        else bad("a key of the wrong length is refused", NULL);
        if (aes_xts_key_create(key, 48) == NULL) ok("a 48-byte key is refused");
        else bad("a 48-byte key is refused", NULL);

        aes_xts_key *k = aes_xts_key_create(key, 64);
        uint8_t tweak[16] = {0}, buf[24] = {0};
        /* Ciphertext stealing is not implemented; a partial block must be
         * refused rather than quietly mangled. */
        if (aes_xts_crypt_sector(k, true, tweak, buf, 24) != 0)
            ok("a length that is not a multiple of the block size is refused");
        else
            bad("a length that is not a multiple of the block size is refused", NULL);
        aes_xts_key_destroy(k);
    }

    /*
     * The JSON reader parses the metadata area of a LUKS2 header, which lives
     * on removable media -- every byte of it is chosen by whoever wrote the
     * disk. So the interesting cases are not the well-formed ones.
     */
    printf("\nJSON, on input nobody friendly wrote\n\n");
    {
        json_tok toks[256];
        struct { const char *name; const char *js; bool should_parse; } cases[] = {
            { "an ordinary object parses",        "{\"a\":1,\"b\":\"x\"}",   true  },
            { "nesting parses",                   "{\"a\":{\"b\":[1,2,{\"c\":3}]}}", true },
            { "an unterminated object is refused", "{\"a\":1",                  false },
            { "an unterminated string is refused", "{\"a\":\"oops}",           false },
            { "a stray closing brace is refused",  "}",                          false },
            { "mismatched brackets are refused",   "{\"a\":[1,2}]",             false },
            { "a control byte is refused",         "{\"a\":\x01}",             false },
        };
        for (size_t i = 0; i < sizeof(cases)/sizeof(cases[0]); i++) {
            int n = json_parse(cases[i].js, strlen(cases[i].js), toks, 256);
            bool parsed = n > 0;
            if (parsed == cases[i].should_parse) ok(cases[i].name);
            else bad(cases[i].name, parsed ? "it parsed and should not have"
                                           : "it was refused and should not have been");
        }

        /* Deep nesting must hit a ceiling rather than the call stack. */
        char deep[4096];
        size_t d = 0;
        for (int i = 0; i < 200 && d < sizeof(deep) - 2; i++) deep[d++] = '[';
        for (int i = 0; i < 200 && d < sizeof(deep) - 1; i++) deep[d++] = ']';
        deep[d] = 0;
        if (json_parse(deep, strlen(deep), toks, 256) < 0)
            ok("nesting deeper than the limit is refused, not recursed into");
        else
            bad("nesting deeper than the limit is refused, not recursed into", NULL);

        /* Running out of tokens must be an error, not a truncated parse. */
        const char *many = "[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]";
        if (json_parse(many, strlen(many), toks, 4) < 0)
            ok("a document too big for the token budget is refused");
        else
            bad("a document too big for the token budget is refused", NULL);

        /* LUKS2 stores byte offsets as strings, because JSON numbers are
         * doubles and these exceed what a double holds exactly. */
        const char *big = "{\"offset\":\"16777216\",\"n\":4096}";
        int n = json_parse(big, strlen(big), toks, 256);
        uint64_t v = 0;
        if (n > 0 && json_get_u64(big, toks, json_object_get(big, toks, n, 0, "offset"), &v) && v == 16777216)
            ok("a number stored as a string is read");
        else
            bad("a number stored as a string is read", NULL);
        if (n > 0 && json_get_u64(big, toks, json_object_get(big, toks, n, 0, "n"), &v) && v == 4096)
            ok("a plain number is read");
        else
            bad("a plain number is read", NULL);

        const char *ovf = "{\"n\":\"99999999999999999999\"}";
        n = json_parse(ovf, strlen(ovf), toks, 256);
        if (n > 0 && !json_get_u64(ovf, toks, json_object_get(ovf, toks, n, 0, "n"), &v))
            ok("a number too large for 64 bits is refused, not wrapped");
        else
            bad("a number too large for 64 bits is refused, not wrapped", NULL);

        /* A key in a nested object must not be found as a key of its parent. */
        const char *nest = "{\"outer\":{\"secret\":1},\"other\":2}";
        n = json_parse(nest, strlen(nest), toks, 256);
        if (n > 0 && json_object_get(nest, toks, n, 0, "secret") < 0)
            ok("a nested key is not mistaken for one of its parent's");
        else
            bad("a nested key is not mistaken for one of its parent's", NULL);
    }

    printf("\nbase64\n\n");
    {
        uint8_t out[64];
        struct { const char *name; const char *in; int want; } b64[] = {
            { "a padded value decodes",        "aGVsbG8=",  5  },
            { "an unpadded multiple decodes",  "aGVsbG8h",  6  },
            { "a bad length is refused",       "aGVsbG8",  -1  },
            { "a non-alphabet byte is refused","aGV*bG8=", -1  },
            { "padding in the middle is refused", "aG=sbG8=", -1 },
        };
        for (size_t i = 0; i < sizeof(b64)/sizeof(b64[0]); i++) {
            int r = base64_decode(b64[i].in, strlen(b64[i].in), out, sizeof(out));
            if (r == b64[i].want) ok(b64[i].name);
            else { char d[64]; snprintf(d, sizeof(d), "want %d got %d", b64[i].want, r); bad(b64[i].name, d); }
        }
        /* Refuse rather than overflow when the output does not fit. */
        if (base64_decode("aGVsbG8gd29ybGQh", 16, out, 4) < 0)
            ok("a value larger than the output buffer is refused");
        else
            bad("a value larger than the output buffer is refused", NULL);
    }

    printf("\n─────────────────────────────────\n");
    printf("passed: %d   failed: %d\n", passed, failed);
    return failed == 0 ? 0 : 1;
}
